[workspace]
channels = ["https://conda.modular.com/max", "conda-forge"]
name = "stimojo"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
benchmarks = "./scripts/mojo_wrap.sh run benchmarks/run_all_benchmarks.mojo"
build = "./scripts/mojo_wrap.sh build benchmarks/run_all_benchmarks.mojo"
example_pauli_string = "./scripts/mojo_wrap.sh run examples/pauli_string.mojo"
example_tableau = "./scripts/mojo_wrap.sh run examples/tableau.mojo"
example_tableau_conjugation = "./scripts/mojo_wrap.sh run examples/tableau_conjugation.mojo"
test_pauli_string = "./scripts/mojo_wrap.sh run test/stimojo/test_pauli_string.mojo"
test_bit_tensor = "./scripts/mojo_wrap.sh run test/stimojo/test_bit_tensor.mojo"
test_ops = "./scripts/mojo_wrap.sh run test/stimojo/test_ops.mojo"
test_tableau = "./scripts/mojo_wrap.sh run test/stimojo/test_tableau.mojo"
test_tableau_ops = "./scripts/mojo_wrap.sh run test/stimojo/test_tableau_ops.mojo"
test_phase = "./scripts/mojo_wrap.sh run test/stimojo/test_phase.mojo"
test_xz_encoding = "./scripts/mojo_wrap.sh run test/stimojo/test_xz_encoding.mojo"
tests = { depends-on = ["test_bit_tensor", "test_xz_encoding", "test_phase", "test_pauli_string", "test_ops", "test_tableau", "test_tableau_ops"] }
format = "mojo format src  test examples benchmarks"

[activation]
env = { STIMOJO_INT_TYPE = "DType.uint64" }

[dependencies]
mojo = "<1.0.0"
