[workspace]
channels = ["https://conda.modular.com/max", "conda-forge"]
name = "stimojo"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"


[tasks]
benchmarks = "mojo run -I src benchmarks/run_all_benchmarks.mojo"
example_pauli_string = "mojo run -I src examples/pauli_string.mojo"
example_tableau = "mojo run -I src examples/tableau.mojo"
example_tableau_conjugation = "mojo run -I src examples/tableau_conjugation.mojo"
test_pauli_string = "mojo run -I src test/stimojo/test_pauli_string.mojo"
test_bit_tensor = "mojo run -I src test/stimojo/test_bit_tensor.mojo"
test_ops = "mojo run -I src test/stimojo/test_ops.mojo"
test_tableau = "mojo run -I src test/stimojo/test_tableau.mojo"
test_tableau_ops = "mojo run -I src test/stimojo/test_tableau_ops.mojo"
test_phase = "mojo run -I src test/stimojo/test_phase.mojo"
test_xz_encoding = "mojo run -I src test/stimojo/test_xz_encoding.mojo"
tests = { depends-on = ["test_pauli_string", "test_bit_tensor", "test_ops", "test_tableau", "test_tableau_ops", "test_phase", "test_xz_encoding"] }
format = "mojo format src  test examples benchmarks"

[dependencies]
mojo = "<1.0.0"
