[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "stimojo"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"


[tasks]
benchmarks = "mojo run src/run_all_benchmarks.mojo"
test_pauli = "mojo run -I src test/stimojo/test_pauli.mojo"
tests = { depends-on = ["test_pauli"] }
format = "mojo format ./src && mojo format ./test"

[dependencies]
mojo = "<1.0.0"
